const profileKeyMapper = [
    {
        title: "PANEL_BUILDER",
        label : "Panel Builder",
        countryId: "Belgium (English)",
        country : "BE",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        title: "ELECTRICIAN",
        label : "Electrician",
        countryId: "Belgium (English)",
        country : "BE",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        title: "CONSUMER",
        label : "End User",
        countryId: "Belgium (English)",
        country : "BE",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        title: "RETAILOR",
        label : "Consumer Retailer",
        countryId: "Belgium (English)",
        country : "BE",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        title: "CONTRACTOR",
        label : "Contractor",
        countryId: "Belgium (English)",
        country : "BE",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        title: "EMPLOYEE",
        label : "Employee",
        countryId: "Belgium (English)",
        country : "BE",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        title: "DIGITAL AND SERVICE PARTNER",
        label : "Digital & Service Partner",
        countryId: "Belgium (English)",
        country : "BE",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        title: "DISTRIBUTOR",
        label : "B2B Distribution",
        countryId: "Belgium (English)",
        country : "BE",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        title: "SPECIFIER",
        label : "Specifier",
        countryId: "Belgium (English)",
        country : "BE",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        title: "SYSTEM_INTEGRATOR",
        label : "System Integrator",
        countryId: "Belgium (English)",
        country : "BE",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        title: "OEM",
        label : "Original Equipment Manufacturer",
        countryId: "Belgium (English)",
        country : "BE",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        title: "RESELLER",
        label : "IT Reseller",
        countryId: "Belgium (English)",
        country : "BE",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    }
]
module.exports = { profileKeyMapper };